package sr.core.history;

import sr.core.vector3.Position;
import sr.core.vector4.Event;

/** 
 The base event for a history defined in terms of <em>displacements</em> from a particular event.

 <em>The delta-base will often exploit a symmetry.</em> 
*/
public class DeltaBase {

  /** 
   Factory method.
   @param ΔbaseEvent from which a history is generated by "deltas".
  */
  public static DeltaBase of(Event ΔbaseEvent) {
    return new DeltaBase(ΔbaseEvent);  
  }

  /** Factory method for the delta-base at the given position, and with <code>ct=0</code>. */
  public static DeltaBase of(Position position) {
    return new DeltaBase(Event.of(0.0, position));  
  }

  /** Factory method to derive a delta-base from an event on a history. */
  public static DeltaBase of(History history, double ct) {
    return new DeltaBase(history.event(ct));  
  }

  /** Factory method using (0,0,0,0) as the delta-base-event. */
  public static DeltaBase origin() {
    return new DeltaBase(Event.of(0.0, Position.of(0.0, 0.0, 0.0)));  
  }
  
  public Event ΔbaseEvent() {return ΔbaseEvent;} 
  
  @Override public String toString() {
    return "DeltaBase event:" + ΔbaseEvent;
  }
  
  protected DeltaBase(Event ΔbaseEvent) {
    this.ΔbaseEvent = ΔbaseEvent;
  }

  private Event ΔbaseEvent;
}
