package sr.core.history;

import sr.core.vector3.Position;
import sr.core.vector4.Event;

/** 
 The base event (and corresponding proper-time) for a history defined in terms of <em>displacements</em> from a particular event.

 <em>The delta-base will often exploit a symmetry.</em> For example,
 <ul> 
   <li>for circular motion, it could be related to the center of the circle. 
   In this case, it's not even part of the history of the object.
   <li>for constant proper-acceleration, it could be the turnaround point. 
 </ul>
*/
public final class DeltaBase {

  /** 
   Factory method.
   @param ΔbaseEvent from which a history is generated by "deltas".
   @param ΔbaseEvent_τ is the value of the proper time for the <code>ΔBaseEvent</code>.  
  */
  public static DeltaBase of(Event ΔbaseEvent, double ΔbaseEvent_τ) {
    return new DeltaBase(ΔbaseEvent, ΔbaseEvent_τ);  
  }

  /** Factory method for the delta-base at the given position, and with <code>ct=0</code> and proper time = 0. */
  public static DeltaBase of(Position position) {
    return new DeltaBase(Event.of(0.0, position), 0.0);  
  }

  /** Factory method to derive a delta-base from an event on a history. */
  public static DeltaBase of(History history, double ct) {
    return new DeltaBase(history.event(ct), history.τ(ct));  
  }

  /** Factory method using (0,0,0,0) as the delta-base-event, with proper time = 0 as well. */
  public static DeltaBase origin() {
    return new DeltaBase(Event.of(0.0, Position.of(0.0, 0.0, 0.0)), 0.0);  
  }
  
  public Event ΔbaseEvent() {return ΔbaseEvent;} 
  public double ΔbaseEvent_τ() {return ΔbaseEvent_τ;}
  
  @Override public String toString() {
    return "DeltaBase event:" + ΔbaseEvent + " τ:" + ΔbaseEvent_τ;
  }
  
  private DeltaBase(Event ΔbaseEvent, double ΔbaseEvent_τ) {
    this.ΔbaseEvent = ΔbaseEvent;
    this.ΔbaseEvent_τ = ΔbaseEvent_τ;
  }
  
  private Event ΔbaseEvent;
  private double ΔbaseEvent_τ;
}
