package sr.core.hist;

import sr.core.component.NEvent;
import sr.core.component.NPosition;

/** 
 The base event for a history defined in terms of <em>displacements</em> from a particular event.

 <em>The delta-base will often exploit a symmetry.</em> 
*/
public class NDeltaBase {

  /** 
   Factory method.
   @param baseEvent from which a history is generated by "deltas".
  */
  public static NDeltaBase of(NEvent baseEvent) {
    return new NDeltaBase(baseEvent);  
  }

  /** Factory method for the delta-base at the given position, and with <code>ct=0</code>. */
  public static NDeltaBase of(NPosition position) {
    return new NDeltaBase(NEvent.of(0.0, position));  
  }

  /** Factory method to derive a delta-base from an event on a history. */
  public static NDeltaBase of(NHistory history, double ct) {
    return new NDeltaBase(history.event(ct));  
  }

  /** Factory method using (0,0,0,0) as the delta-base-event. */
  public static NDeltaBase origin() {
    return new NDeltaBase(NEvent.of(0.0, NPosition.of(0.0, 0.0, 0.0)));  
  }
  
  public NEvent baseEvent() {return baseEvent;} 
  
  @Override public String toString() {
    return baseEvent.toString();
  }
  
  protected NDeltaBase(NEvent ΔbaseEvent) {
    this.baseEvent = ΔbaseEvent;
  }

  private NEvent baseEvent;
}
